/*
 * Copyright (C) 2026 The WayDroid-ATV Project
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <fstream>
#include <string>
#include <vector>
#include <cstring>
#include <cerrno>

#include "log.h"
#include "waydroid_prop.h"

#define WAYDROID_PROP "/vendor/waydroid.prop"

WaydroidProp::WaydroidProp(const std::vector<std::string> &props) {
    std::string propLine;
    size_t      delim;

    propFile.open(WAYDROID_PROP, std::ios::in | std::ios::out);

    if (!propFile.is_open()) {
        Log::err("Failed to open waydroid.prop: {}", strerror(errno));
        exit(errno);
    }

    while (std::getline(propFile, propLine)) {
        if ((delim = propLine.find('=')) == std::string::npos) continue;

        std::string key = propLine.substr(0, delim);
        if (!key.starts_with("#")) properties[key] = propLine.substr(delim + 1);
    }

    for (const auto &line : props) {
        if ((delim = line.find('=')) == std::string::npos) continue;

        std::string key = line.substr(0, delim);
        if (!key.starts_with("#")) properties[key] = line.substr(delim + 1);
    }
}

std::string WaydroidProp::getProperty(const std::string &prop) const {
    auto it = properties.find(prop);
    if (it != properties.end()) return it->second;
    return "";
}

void WaydroidProp::setProperty(const std::string &prop, const std::string &value) {
    properties[prop] = value;
}

void WaydroidProp::saveProperties() {
    if (!propFile.is_open()) return;

    propFile.clear();
    propFile.seekg(0, std::ios::beg);
    propFile << "# Auto-generated by waydroid-preinit" << std::endl;

    for (const auto &[prop, value] : properties) {
        propFile << prop << "=" << value << std::endl;
    }

    propFile.close();
}
